package anuri.modelo;
// Generated 12-oct-2015 19:44:16 by Hibernate Tools 4.0.0

/**
 * Permiso generated by hbm2java
 */
public class Permiso implements java.io.Serializable {

	private Integer permisoId;
	private String nombre;

	public Permiso() {
	}

	public Permiso(String nombre) {
		this.nombre = nombre;
	}

	public Integer getPermisoId() {
		return this.permisoId;
	}

	public void setPermisoId(Integer permisoId) {
		this.permisoId = permisoId;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

}
