package anuri.modelo;
// Generated 12-oct-2015 19:44:16 by Hibernate Tools 4.0.0

/**
 * UserPermiso generated by hbm2java
 */
public class UserPermiso implements java.io.Serializable {

	private Integer userPermisoId;
	private int userId;
	private int permisoId;

	public UserPermiso() {
	}

	public UserPermiso(int userId, int permisoId) {
		this.userId = userId;
		this.permisoId = permisoId;
	}

	public Integer getUserPermisoId() {
		return this.userPermisoId;
	}

	public void setUserPermisoId(Integer userPermisoId) {
		this.userPermisoId = userPermisoId;
	}

	public int getUserId() {
		return this.userId;
	}

	public void setUserId(int userId) {
		this.userId = userId;
	}

	public int getPermisoId() {
		return this.permisoId;
	}

	public void setPermisoId(int permisoId) {
		this.permisoId = permisoId;
	}

}
