package modelo;
// Generated 19-oct-2015 19:13:07 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

/**
 * Permiso generated by hbm2java
 */
public class Permiso implements java.io.Serializable {

	private Integer permisoId;
	private String nombre;
	private Set<User> users = new HashSet<User>(0);

	public Permiso() {
	}

	public Permiso(String nombre) {
		this.nombre = nombre;
	}

	public Integer getPermisoId() {
		return this.permisoId;
	}

	public void setPermisoId(Integer permisoId) {
		this.permisoId = permisoId;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public Set<User> getUsers() {
		return users;
	}

	public void setUsers(Set<User> user) {
		this.users = user;
	}
	
	public void setUsers(User user) {
		this.users.add(user);
	}

}
