package modelo;
// Generated 19-oct-2015 19:13:07 by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;
/**
 * User generated by hbm2java
 */
public class User implements java.io.Serializable {

	private Integer userId;
	private String nombre;
	private char[] password;
	private Set<Permiso> permisos = new HashSet<Permiso>(0);

	
	public User() {
	}

	public User(String nombre, char[] password) {
		this.nombre = nombre;
		this.password = password;
	}

	public Integer getUserId() {
		return this.userId;
	}

	public void setUserId(Integer userId) {
		this.userId = userId;
	}

	public String getNombre() {
		return this.nombre;
	}

	public void setNombre(String nombre) {
		this.nombre = nombre;
	}

	public char[] getPassword() {
		return this.password;
	}

	public void setPassword(char[] password) {
		this.password = password;
	}

	public Set<Permiso> getPermisos() {
		return permisos;
	}

	public void setPermisos(Set<Permiso> permisos) {
		this.permisos = permisos;
	}

	public void addPermisos(Permiso permisos) {
		this.permisos.add(permisos);
	}

}
